### ISSUE TITLE
Не отображается исполнитель в карточке трека

### ISSUE THREAD

**Issue by vtsisyk** [neochapay/YaSailMusic#11]
Аврора 5rc4, Наша Музыка 0.3.5

![player_card_no_author](https://github.com/neochapay/AuroraYandexMusic/assets/30614987/65021239-dea5-4719-9014-f0780703c3cd)

Если открыть плеер с текущим треком, то не отображается исполнитель.

**Comment by neochapay** [comment]
Fixed
