### ISSUE TITLE
В первом результате поиска текст перекрывается другим текстом

### ISSUE THREAD

**Issue by vtsisyk** [neochapay/YaSailMusic#12]
Аврора 5rc4, Наша Музыка 0.3.5

![player_search_mashed](https://github.com/neochapay/AuroraYandexMusic/assets/30614987/55755c47-1dd0-4ecd-b467-1544978f6bdb)

На картинке хорошо видно, что в первом результате какой-то мусор. Еще кажется, будто там неправильный текст, помимо правильного.

**Comment by neochapay** [comment]
Fixed
