### ISSUE TITLE
Убрать текст на обложке альбома

### ISSUE THREAD

**Issue by vtsisyk** [neochapay/YaSailMusic#15]
Аврора 5rc4, Наша Музыка 0.3.5

Если открывать альбом(сейчас это можно сделать при помощи раздела "Новые релизы"), то на обложке будет написано его название. Я предлагаю это убрать или переработать потому что:
1. текст плохо читается на некоторых типах обложек;
2. название альбома есть, а исполнителя нет;
3. подобное решение портит эстетическое восприятие обложки

**Comment by neochapay** [comment]
fixed
