### ISSUE TITLE
Заикается звук при первом проигрывании трэка

### ISSUE THREAD

**Issue by alpha6** [neochapay/YaSailMusic#16]
1.  С главного экрана зайти в плейлист
2. Нажать копку прогрывания трека

Текущее поведение: Трек начинает возпроизводиться сразу, при этом есть треск и заикания. Длятся в течении пары секунд, дальше воспроизводится нормально.

Ожидаемое поведение: Трек воспроизводится нормально,

Возможно стоит воспроизвести поведение андроид клиента, когда трек не начинает воспроизводиться пока какая-то часть его не попадет в кэш.

**Comment by neochapay** [comment]
Fixed in 0.3.8

**Comment by cypa** [comment]
а как обновиться до этой версии? 
у меня сейчас 0.3.6-0 установлена из магазина ОМП
