### ISSUE TITLE
bugs

### ISSUE THREAD

**Issue by writer22rus** [neochapay/YaSailMusic#3]
1. При переключении между треками кнопками управления временной лаг 5-10 сек между нажатием кнопки и переключением на другой трек
2. В плейлисте отображается только 5 треков, еще 3 догружаются, при переключении на пятый трек и т.п.
3. Если свернуть приложение, а потом с рабочего стола попытаться к нему вернуться, оно просто закрывается

**Comment by RZA2008** [comment]
Не подгружаются плейлисты

**Comment by dimoon91** [comment]
Приложение вылетает при попытке воспроизведения трека из поисковой выдачи.

**Comment by neochapay** [comment]
fixed
